// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DemoonLXW/up_learning/database/ent/class"
	"github.com/DemoonLXW/up_learning/database/ent/college"
	"github.com/DemoonLXW/up_learning/database/ent/predicate"
)

// ClassUpdate is the builder for updating Class entities.
type ClassUpdate struct {
	config
	hooks    []Hook
	mutation *ClassMutation
}

// Where appends a list predicates to the ClassUpdate builder.
func (cu *ClassUpdate) Where(ps ...predicate.Class) *ClassUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetCid sets the "cid" field.
func (cu *ClassUpdate) SetCid(u uint16) *ClassUpdate {
	cu.mutation.SetCid(u)
	return cu
}

// SetName sets the "name" field.
func (cu *ClassUpdate) SetName(s string) *ClassUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetIsDisabled sets the "is_disabled" field.
func (cu *ClassUpdate) SetIsDisabled(b bool) *ClassUpdate {
	cu.mutation.SetIsDisabled(b)
	return cu
}

// SetNillableIsDisabled sets the "is_disabled" field if the given value is not nil.
func (cu *ClassUpdate) SetNillableIsDisabled(b *bool) *ClassUpdate {
	if b != nil {
		cu.SetIsDisabled(*b)
	}
	return cu
}

// SetCreatedTime sets the "created_time" field.
func (cu *ClassUpdate) SetCreatedTime(t time.Time) *ClassUpdate {
	cu.mutation.SetCreatedTime(t)
	return cu
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (cu *ClassUpdate) SetNillableCreatedTime(t *time.Time) *ClassUpdate {
	if t != nil {
		cu.SetCreatedTime(*t)
	}
	return cu
}

// SetDeletedTime sets the "deleted_time" field.
func (cu *ClassUpdate) SetDeletedTime(t time.Time) *ClassUpdate {
	cu.mutation.SetDeletedTime(t)
	return cu
}

// SetNillableDeletedTime sets the "deleted_time" field if the given value is not nil.
func (cu *ClassUpdate) SetNillableDeletedTime(t *time.Time) *ClassUpdate {
	if t != nil {
		cu.SetDeletedTime(*t)
	}
	return cu
}

// ClearDeletedTime clears the value of the "deleted_time" field.
func (cu *ClassUpdate) ClearDeletedTime() *ClassUpdate {
	cu.mutation.ClearDeletedTime()
	return cu
}

// SetModifiedTime sets the "modified_time" field.
func (cu *ClassUpdate) SetModifiedTime(t time.Time) *ClassUpdate {
	cu.mutation.SetModifiedTime(t)
	return cu
}

// SetNillableModifiedTime sets the "modified_time" field if the given value is not nil.
func (cu *ClassUpdate) SetNillableModifiedTime(t *time.Time) *ClassUpdate {
	if t != nil {
		cu.SetModifiedTime(*t)
	}
	return cu
}

// ClearModifiedTime clears the value of the "modified_time" field.
func (cu *ClassUpdate) ClearModifiedTime() *ClassUpdate {
	cu.mutation.ClearModifiedTime()
	return cu
}

// SetCollegeID sets the "college" edge to the College entity by ID.
func (cu *ClassUpdate) SetCollegeID(id uint16) *ClassUpdate {
	cu.mutation.SetCollegeID(id)
	return cu
}

// SetCollege sets the "college" edge to the College entity.
func (cu *ClassUpdate) SetCollege(c *College) *ClassUpdate {
	return cu.SetCollegeID(c.ID)
}

// Mutation returns the ClassMutation object of the builder.
func (cu *ClassUpdate) Mutation() *ClassMutation {
	return cu.mutation
}

// ClearCollege clears the "college" edge to the College entity.
func (cu *ClassUpdate) ClearCollege() *ClassUpdate {
	cu.mutation.ClearCollege()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ClassUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ClassUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ClassUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ClassUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ClassUpdate) check() error {
	if _, ok := cu.mutation.CollegeID(); cu.mutation.CollegeCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Class.college"`)
	}
	return nil
}

func (cu *ClassUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(class.Table, class.Columns, sqlgraph.NewFieldSpec(class.FieldID, field.TypeUint32))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(class.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.IsDisabled(); ok {
		_spec.SetField(class.FieldIsDisabled, field.TypeBool, value)
	}
	if value, ok := cu.mutation.CreatedTime(); ok {
		_spec.SetField(class.FieldCreatedTime, field.TypeTime, value)
	}
	if value, ok := cu.mutation.DeletedTime(); ok {
		_spec.SetField(class.FieldDeletedTime, field.TypeTime, value)
	}
	if cu.mutation.DeletedTimeCleared() {
		_spec.ClearField(class.FieldDeletedTime, field.TypeTime)
	}
	if value, ok := cu.mutation.ModifiedTime(); ok {
		_spec.SetField(class.FieldModifiedTime, field.TypeTime, value)
	}
	if cu.mutation.ModifiedTimeCleared() {
		_spec.ClearField(class.FieldModifiedTime, field.TypeTime)
	}
	if cu.mutation.CollegeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.CollegeTable,
			Columns: []string{class.CollegeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(college.FieldID, field.TypeUint16),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.CollegeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.CollegeTable,
			Columns: []string{class.CollegeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(college.FieldID, field.TypeUint16),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ClassUpdateOne is the builder for updating a single Class entity.
type ClassUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClassMutation
}

// SetCid sets the "cid" field.
func (cuo *ClassUpdateOne) SetCid(u uint16) *ClassUpdateOne {
	cuo.mutation.SetCid(u)
	return cuo
}

// SetName sets the "name" field.
func (cuo *ClassUpdateOne) SetName(s string) *ClassUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetIsDisabled sets the "is_disabled" field.
func (cuo *ClassUpdateOne) SetIsDisabled(b bool) *ClassUpdateOne {
	cuo.mutation.SetIsDisabled(b)
	return cuo
}

// SetNillableIsDisabled sets the "is_disabled" field if the given value is not nil.
func (cuo *ClassUpdateOne) SetNillableIsDisabled(b *bool) *ClassUpdateOne {
	if b != nil {
		cuo.SetIsDisabled(*b)
	}
	return cuo
}

// SetCreatedTime sets the "created_time" field.
func (cuo *ClassUpdateOne) SetCreatedTime(t time.Time) *ClassUpdateOne {
	cuo.mutation.SetCreatedTime(t)
	return cuo
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (cuo *ClassUpdateOne) SetNillableCreatedTime(t *time.Time) *ClassUpdateOne {
	if t != nil {
		cuo.SetCreatedTime(*t)
	}
	return cuo
}

// SetDeletedTime sets the "deleted_time" field.
func (cuo *ClassUpdateOne) SetDeletedTime(t time.Time) *ClassUpdateOne {
	cuo.mutation.SetDeletedTime(t)
	return cuo
}

// SetNillableDeletedTime sets the "deleted_time" field if the given value is not nil.
func (cuo *ClassUpdateOne) SetNillableDeletedTime(t *time.Time) *ClassUpdateOne {
	if t != nil {
		cuo.SetDeletedTime(*t)
	}
	return cuo
}

// ClearDeletedTime clears the value of the "deleted_time" field.
func (cuo *ClassUpdateOne) ClearDeletedTime() *ClassUpdateOne {
	cuo.mutation.ClearDeletedTime()
	return cuo
}

// SetModifiedTime sets the "modified_time" field.
func (cuo *ClassUpdateOne) SetModifiedTime(t time.Time) *ClassUpdateOne {
	cuo.mutation.SetModifiedTime(t)
	return cuo
}

// SetNillableModifiedTime sets the "modified_time" field if the given value is not nil.
func (cuo *ClassUpdateOne) SetNillableModifiedTime(t *time.Time) *ClassUpdateOne {
	if t != nil {
		cuo.SetModifiedTime(*t)
	}
	return cuo
}

// ClearModifiedTime clears the value of the "modified_time" field.
func (cuo *ClassUpdateOne) ClearModifiedTime() *ClassUpdateOne {
	cuo.mutation.ClearModifiedTime()
	return cuo
}

// SetCollegeID sets the "college" edge to the College entity by ID.
func (cuo *ClassUpdateOne) SetCollegeID(id uint16) *ClassUpdateOne {
	cuo.mutation.SetCollegeID(id)
	return cuo
}

// SetCollege sets the "college" edge to the College entity.
func (cuo *ClassUpdateOne) SetCollege(c *College) *ClassUpdateOne {
	return cuo.SetCollegeID(c.ID)
}

// Mutation returns the ClassMutation object of the builder.
func (cuo *ClassUpdateOne) Mutation() *ClassMutation {
	return cuo.mutation
}

// ClearCollege clears the "college" edge to the College entity.
func (cuo *ClassUpdateOne) ClearCollege() *ClassUpdateOne {
	cuo.mutation.ClearCollege()
	return cuo
}

// Where appends a list predicates to the ClassUpdate builder.
func (cuo *ClassUpdateOne) Where(ps ...predicate.Class) *ClassUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ClassUpdateOne) Select(field string, fields ...string) *ClassUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Class entity.
func (cuo *ClassUpdateOne) Save(ctx context.Context) (*Class, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ClassUpdateOne) SaveX(ctx context.Context) *Class {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ClassUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ClassUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ClassUpdateOne) check() error {
	if _, ok := cuo.mutation.CollegeID(); cuo.mutation.CollegeCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Class.college"`)
	}
	return nil
}

func (cuo *ClassUpdateOne) sqlSave(ctx context.Context) (_node *Class, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(class.Table, class.Columns, sqlgraph.NewFieldSpec(class.FieldID, field.TypeUint32))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Class.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, class.FieldID)
		for _, f := range fields {
			if !class.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != class.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(class.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.IsDisabled(); ok {
		_spec.SetField(class.FieldIsDisabled, field.TypeBool, value)
	}
	if value, ok := cuo.mutation.CreatedTime(); ok {
		_spec.SetField(class.FieldCreatedTime, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.DeletedTime(); ok {
		_spec.SetField(class.FieldDeletedTime, field.TypeTime, value)
	}
	if cuo.mutation.DeletedTimeCleared() {
		_spec.ClearField(class.FieldDeletedTime, field.TypeTime)
	}
	if value, ok := cuo.mutation.ModifiedTime(); ok {
		_spec.SetField(class.FieldModifiedTime, field.TypeTime, value)
	}
	if cuo.mutation.ModifiedTimeCleared() {
		_spec.ClearField(class.FieldModifiedTime, field.TypeTime)
	}
	if cuo.mutation.CollegeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.CollegeTable,
			Columns: []string{class.CollegeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(college.FieldID, field.TypeUint16),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.CollegeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   class.CollegeTable,
			Columns: []string{class.CollegeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(college.FieldID, field.TypeUint16),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Class{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
