// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DemoonLXW/up_learning/database/ent/class"
	"github.com/DemoonLXW/up_learning/database/ent/college"
	"github.com/DemoonLXW/up_learning/database/ent/predicate"
	"github.com/DemoonLXW/up_learning/database/ent/school"
)

// CollegeQuery is the builder for querying College entities.
type CollegeQuery struct {
	config
	ctx         *QueryContext
	order       []college.OrderOption
	inters      []Interceptor
	predicates  []predicate.College
	withSchool  *SchoolQuery
	withClasses *ClassQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CollegeQuery builder.
func (cq *CollegeQuery) Where(ps ...predicate.College) *CollegeQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CollegeQuery) Limit(limit int) *CollegeQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CollegeQuery) Offset(offset int) *CollegeQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CollegeQuery) Unique(unique bool) *CollegeQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CollegeQuery) Order(o ...college.OrderOption) *CollegeQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QuerySchool chains the current query on the "school" edge.
func (cq *CollegeQuery) QuerySchool() *SchoolQuery {
	query := (&SchoolClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(college.Table, college.FieldID, selector),
			sqlgraph.To(school.Table, school.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, college.SchoolTable, college.SchoolColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryClasses chains the current query on the "classes" edge.
func (cq *CollegeQuery) QueryClasses() *ClassQuery {
	query := (&ClassClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(college.Table, college.FieldID, selector),
			sqlgraph.To(class.Table, class.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, college.ClassesTable, college.ClassesColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first College entity from the query.
// Returns a *NotFoundError when no College was found.
func (cq *CollegeQuery) First(ctx context.Context) (*College, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{college.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CollegeQuery) FirstX(ctx context.Context) *College {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first College ID from the query.
// Returns a *NotFoundError when no College ID was found.
func (cq *CollegeQuery) FirstID(ctx context.Context) (id uint16, err error) {
	var ids []uint16
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{college.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CollegeQuery) FirstIDX(ctx context.Context) uint16 {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single College entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one College entity is found.
// Returns a *NotFoundError when no College entities are found.
func (cq *CollegeQuery) Only(ctx context.Context) (*College, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{college.Label}
	default:
		return nil, &NotSingularError{college.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CollegeQuery) OnlyX(ctx context.Context) *College {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only College ID in the query.
// Returns a *NotSingularError when more than one College ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CollegeQuery) OnlyID(ctx context.Context) (id uint16, err error) {
	var ids []uint16
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{college.Label}
	default:
		err = &NotSingularError{college.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CollegeQuery) OnlyIDX(ctx context.Context) uint16 {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Colleges.
func (cq *CollegeQuery) All(ctx context.Context) ([]*College, error) {
	ctx = setContextOp(ctx, cq.ctx, "All")
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*College, *CollegeQuery]()
	return withInterceptors[[]*College](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CollegeQuery) AllX(ctx context.Context) []*College {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of College IDs.
func (cq *CollegeQuery) IDs(ctx context.Context) (ids []uint16, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, "IDs")
	if err = cq.Select(college.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CollegeQuery) IDsX(ctx context.Context) []uint16 {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CollegeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, "Count")
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CollegeQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CollegeQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CollegeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, "Exist")
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CollegeQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CollegeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CollegeQuery) Clone() *CollegeQuery {
	if cq == nil {
		return nil
	}
	return &CollegeQuery{
		config:      cq.config,
		ctx:         cq.ctx.Clone(),
		order:       append([]college.OrderOption{}, cq.order...),
		inters:      append([]Interceptor{}, cq.inters...),
		predicates:  append([]predicate.College{}, cq.predicates...),
		withSchool:  cq.withSchool.Clone(),
		withClasses: cq.withClasses.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithSchool tells the query-builder to eager-load the nodes that are connected to
// the "school" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CollegeQuery) WithSchool(opts ...func(*SchoolQuery)) *CollegeQuery {
	query := (&SchoolClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withSchool = query
	return cq
}

// WithClasses tells the query-builder to eager-load the nodes that are connected to
// the "classes" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CollegeQuery) WithClasses(opts ...func(*ClassQuery)) *CollegeQuery {
	query := (&ClassClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withClasses = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Sid uint16 `json:"sid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.College.Query().
//		GroupBy(college.FieldSid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CollegeQuery) GroupBy(field string, fields ...string) *CollegeGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CollegeGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = college.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Sid uint16 `json:"sid,omitempty"`
//	}
//
//	client.College.Query().
//		Select(college.FieldSid).
//		Scan(ctx, &v)
func (cq *CollegeQuery) Select(fields ...string) *CollegeSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CollegeSelect{CollegeQuery: cq}
	sbuild.label = college.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CollegeSelect configured with the given aggregations.
func (cq *CollegeQuery) Aggregate(fns ...AggregateFunc) *CollegeSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CollegeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !college.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CollegeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*College, error) {
	var (
		nodes       = []*College{}
		_spec       = cq.querySpec()
		loadedTypes = [2]bool{
			cq.withSchool != nil,
			cq.withClasses != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*College).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &College{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withSchool; query != nil {
		if err := cq.loadSchool(ctx, query, nodes, nil,
			func(n *College, e *School) { n.Edges.School = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withClasses; query != nil {
		if err := cq.loadClasses(ctx, query, nodes,
			func(n *College) { n.Edges.Classes = []*Class{} },
			func(n *College, e *Class) { n.Edges.Classes = append(n.Edges.Classes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CollegeQuery) loadSchool(ctx context.Context, query *SchoolQuery, nodes []*College, init func(*College), assign func(*College, *School)) error {
	ids := make([]uint16, 0, len(nodes))
	nodeids := make(map[uint16][]*College)
	for i := range nodes {
		fk := nodes[i].Sid
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(school.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sid" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *CollegeQuery) loadClasses(ctx context.Context, query *ClassQuery, nodes []*College, init func(*College), assign func(*College, *Class)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint16]*College)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(class.FieldCid)
	}
	query.Where(predicate.Class(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(college.ClassesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.Cid
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "cid" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *CollegeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CollegeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(college.Table, college.Columns, sqlgraph.NewFieldSpec(college.FieldID, field.TypeUint16))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, college.FieldID)
		for i := range fields {
			if fields[i] != college.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if cq.withSchool != nil {
			_spec.Node.AddColumnOnce(college.FieldSid)
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CollegeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(college.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = college.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CollegeGroupBy is the group-by builder for College entities.
type CollegeGroupBy struct {
	selector
	build *CollegeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CollegeGroupBy) Aggregate(fns ...AggregateFunc) *CollegeGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CollegeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, "GroupBy")
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CollegeQuery, *CollegeGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CollegeGroupBy) sqlScan(ctx context.Context, root *CollegeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CollegeSelect is the builder for selecting fields of College entities.
type CollegeSelect struct {
	*CollegeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CollegeSelect) Aggregate(fns ...AggregateFunc) *CollegeSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CollegeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, "Select")
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CollegeQuery, *CollegeSelect](ctx, cs.CollegeQuery, cs, cs.inters, v)
}

func (cs *CollegeSelect) sqlScan(ctx context.Context, root *CollegeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
